### PR TITLE
[cmake] Add support for MSVC

### PR DESCRIPTION
**Pull request by xoofx**
This is a followup of the previous PR #69 in order to bring support for MSVC. 

I will use this PR to get appveyor working.

### CODE REVIEW

**Comment by xoofx** [comment]
Ok, we just got our first [SLEEF appveyor build working](https://ci.appveyor.com/project/shibatch/sleef/build/artifacts)

**Comment by xoofx** [comment]
I have squashed the commits, rebase of a fix on latest #69 and push force

**Comment by xoofx** [comment]
Build should be green, as it hasn't changed anything from #69 but there is [an error on the GCC build](https://travis-ci.org/shibatch/sleef/jobs/279911625), related to an invalid version of cmake. Seems like a build/setup/travis temp issue.

**Comment by xoofx** [comment]
@fpetrogalli-arm  Ok, looks like I'm gonna have to rebase all the branches for #70, #72, and #73 as github doesn't track things correctly. But I will do it one by step otherwise I will have to do multiple rebases and pushes, which is super annoying...
Let me know how we can proceed.

**Comment by fpetrogalli-arm** [comment]
@fpetrogalli-arm<https://github.com/fpetrogalli-arm> Ok, looks like I'm gonna have to rebase all the branches for #70<https://github.com/shibatch/sleef/pull/70>, #72<https://github.com/shibatch/sleef/pull/72>, and #73<https://github.com/shibatch/sleef/pull/73> as github doesn't track things correctly. But I will do it one by step otherwise I will have to do multiple rebases and pushes, which is super annoying...
Let me know how we can proceed.

Please do the rebase so we need to review only the new commits. It is going to be sequential, I know, sorry about that, but it will make things easier to review.

IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Thank you.

**Comment by xoofx** [comment]
> Please do the rebase so we need to review only the new commits. It is going to be sequential, I know, sorry about that, but it will make things easier to review.

Done.

**Comment by xoofx** [comment]
> Feel free to merge this once CI is green. Thanks.

I can't merge it myself but it is green 😅

**Comment by shibatch** [comment]
@xoofx I now added you as a collaborator.

**Comment by xoofx** [comment]
> @xoofx I now added you as a collaborator.

Wow, that's really cool @shibatch thanks, I appreciate. I will follow the PR process the same way, just it will help to merge the final bits once it's passing review.

**Pull request merged**
