### PR TITLE
[Benchmark] New benchmarking tool with gnuplot

### PR DESCRIPTION
**Pull request by shibatch**
This patch replaces the old benchmarking tool with a new tool with gnuplot.

With this new tool, the graph showing execution time can be automatically drawn.
It is now easy to see the difference between different library versions or compilers.
Some results are shown at http://shibatch.github.io/

This patch implements the tool described in https://github.com/shibatch/sleef/issues/9.
I am planning to add another benchmarking tool based on the Google microbenchmarking framework.

### CODE REVIEW

**Comment by fpetrogalli-arm** [comment]
Are these benchmarks specific to Intel? In #9 the idea was to write micro-benchmark that could work on any architecture, using the googletest tool as agreed, and using the same mechanisms of the helper header files that is used to write target independent tests.

Please make sure they build (not run!) on the Travis-CI machines. I might have missed it, but I can't see the build output on CI.

**Comment by shibatch** [comment]
At this point, the benchmarking tool is specific to Intel. I am planning to expose all functions with names without vector extension name, and after making that change, it will support ARM.

I was also looking for a way to run the benchmarking tool on travis, but how do you think about this? It requires an Amazon S3 account, but a free license expires after the first 12 months.

**Comment by fpetrogalli-arm** [comment]
@shibatch , I understand that these are the benchmarks that are used to produce the figures for release 3.2, as explained in #147. Please rebase against master and build them with cmake. Don't merge master, otherwise it will be cumbersome as all the changes since the PR will be shown. Also, I would like to break the contents in two separate folders:
1. put the benchmark code in src/libm-benchmarks
2. put the java/gnuplot tools in src/libm-benchmarks/plot-scripts

**Comment by shibatch** [comment]
Rebased. The new PR is https://github.com/shibatch/sleef/pull/168.

**Pull request closed without merging**
