### PR TITLE
[cmake] Cosmetic changes.

### PR DESCRIPTION
**Pull request by fpetrogalli-arm**
Changes included in this patch set:

* Use `SLEEF_C_FLAGS` to group the flags required to compile sleef, and
   print them at configuration time.
* Remove unused variables: `FLAGS_OPENMP`, `FLAGS_FASTMATH`.
* More verbose configure output. The verbose output is activated by default.
   It also prompts target and host systems, and the full path of the C compiler.
* The `SLEEF_OSTYPE` variable was unset, so I replace it with the equivalent
   one provided by cmake, `CMAKE_SYSTEM`.

### CODE REVIEW

**Comment by xoofx** [comment]
@fpetrogalli-arm hi, I haven't checked the status of the `cmake-transition` branch, but is it usable? What is remaining left? As I would like to generate pure LLVM bitcode, I feel more comfortable to do it cleanly in a cmake environment...

**Comment by shibatch** [comment]
Hi @xoofx,
Unfortunately, this branch is far from complete. It was mainly developed by @diaena, but the development is suspended since her intern period is now over. I hope she will come back and continue development.

**Comment by fpetrogalli-arm** [comment]
Hello @xoofx,

Yes, as @shibatch says, there is still stuff to do but I believe that the cmake system is usable on x86 and aarch64 Linux. This should allow you to embed SLEEF in LLVM and get bitcode out of it. Feel free to raise an issue for that, where we can discuss how to proceed and eventually how to merge it when ready.

I am looking forward to see SLEEF into LLVM! I am interested to see in which part of LLVM you want to see it. We can move the discussion to the issue you raise, better not to do it in the pull request.

**Comment by xoofx** [comment]
> Yes, as @shibatch says, there is still stuff to do but I believe that the cmake system is usable on x86 and aarch64 Linux. This should allow you to embed SLEEF in LLVM and get bitcode out of it. Feel free to raise an issue for that, where we can discuss how to proceed and eventually how to merge it when ready.

Thanks! So I will try the cmake branch then. If I can upstream the options to generate LLVM IR files only, I will try.

> I am looking forward to see SLEEF into LLVM! I am interested to see in which part of LLVM you want to see it. We can move the discussion to the issue you raise, better not to do it in the pull request.

I'm just looking to be able to use SLEEF functions linked with some existing LLVM bitcode (that is currently generated by JIT), and let the LLVM IR optimizer do the rest (typically, let the vectorizer, or any relevant IR optimizations to apply when linking the different IR modules together)

 @shibatch apart for reading the existing Makefile, is there any documentation/existing github issue, that could explain a bit the logic behind the build process? (I can see some concatenation of files into the sleef.h api, some rename occuring...etc.) Just to get a rough idea about the process...

**Comment by shibatch** [comment]
> @shibatch apart for reading the existing Makefile, is there any documentation/existing github issue, that could explain a bit the logic behind the build process? (I can see some concatenation of files into the sleef.h api, some rename occuring...etc.) Just to get a rough idea about the process...

There is no documentation on how the makefile works. Since we had a plan to migrate to cmake before release of 3.1, I didn't write anything about it. Could you tell me what information you need?

**Comment by xoofx** [comment]
> There is no documentation on how the makefile works. Since we had a plan to migrate to cmake before release of 3.1, I didn't write anything about it. Could you tell me what information you need?

No worries, I will find out looking at the cmake, if I can extract some relevant infos, I will open a PR.

**Pull request merged**
