### PR TITLE
[gnuabi] Enable "finite" names (Double Precision).

### PR DESCRIPTION
**Pull request by fpetrogalli-arm**
glibc/libm defines "finite" names for some of the C99 functions.

### CODE REVIEW

**Comment by fpetrogalli-arm** [comment]
@shibatch , gentle ping.

**Comment by fpetrogalli-arm** [comment]
OK, I'll rework the patch. I didn't use aliases because I wanted to make it generic for any compiler - I believe that aliases work only for gcc and clang. This is fine by me. Thank you for your feedback.

**Comment by shibatch** [comment]
I thought the current code is acceptable if the generated code is exactly the same. So, I now checked if gcc generates the same code for the two functions in a similar situation. It generates an extra jmp instruction for the second function. It could worsen in more complex situations, so I think it is better to take a measure at this time.

**Comment by fpetrogalli-arm** [comment]
The current code uses aliases, there should not be any performance change. This set of patches are only for double precision, I will add the single precision ones when you are happy. I have added a test that checks the presence of the finite symbols in `libsleefgnuabi`.

**Comment by fpetrogalli-arm** [comment]
@shibatch, gentle ping.

**Comment by shibatch** [comment]
What I was thinking is that availability of alias attribute is checked within cmake or by checking the OS type, and it switches between the #define version and the alias version. How do you think?

**Comment by fpetrogalli-arm** [comment]
That's reasonable, but the cmake build system is still incomplete, I want to do it in the Makefile system. Here is is safe to assume that ENABLE_GNUABI implies the availability of the `alias` attribute.

**Comment by shibatch** [comment]
I thought that the problem occurs with OSX?

**Pull request merged**
