### PR TITLE
Add power9 support

### PR DESCRIPTION
**Pull request by shibatch**
This patch adds POWER9 support as mentioned in issue https://github.com/shibatch/sleef/issues/313.

### CODE REVIEW

**Comment by RajalakshmiSR** [comment]
Thanks @shibatch for adding this. I am able to see -mcpu=power9 in the build log on POWER9. 
However, when I run 'make test' with this patch on POWER8 system, I could still see the new vsx3 tests in log. Is this expected?

**Comment by shibatch** [comment]
@RajalakshmiSR Yes. If the IUT successfully detects that the corresponding vector extension is not available, it exits with SUCCESS code, displaying the following message.

```
[sleef-ppc64]~/work/sleef3/sleef-power9/build-ppc64le/bin$ ./iutvsx3


***** This host does not support the necessary CPU features to execute this program *****


0
[sleef-ppc64]~/work/sleef3/sleef-power9/build-ppc64le/bin$ ./tester ./iutvsx3


*** Now testing ./iutvsx3


***** This host does not support the necessary CPU features to execute this program *****




Tester : *** CPU does not support the necessary feature
[sleef-ppc64]~/work/sleef3/sleef-power9/build-ppc64le/bin$
```

**Comment by RajalakshmiSR** [comment]
@shibatch There are some ifdefs for clang and gcc in helperpower_128.h. 
Gcc 7 supports vec_xxpermdi , __builtin_vsx_xvcvsxwdp, __builtin_vsx_xvcvdpsxws. If we expect minimum gcc version as 7, then we can remove the differences between clang and gcc. (Tried with ubuntu gcc 7.5)
Also __builtin_convertvector and  vec_neg are available in GCC9 . So when we add minimum gcc version as 9, we can just make that code common for both clang and gcc.

**Comment by shibatch** [comment]
Those built-in functions are now used according to the gcc version by checking __GNUC__ macro.
I manually ran the tests on gcc-6, gcc-7 and gcc-9, and they all worked.

**Comment by RajalakshmiSR** [comment]
LGTM. Thanks @shibatch

**Comment by shibatch** [comment]
Merged. Thank you for reviewing.

**Pull request merged**
