### PR TITLE
[Makefile] Remove makefiles

### PR DESCRIPTION
**Pull request by shibatch**
This patch removes reduces functionality of makefiles. They are not removed since we still need them for cleaning up.

The location of sleefdft.h is changed from include to src/dft/include. CMakefiles are changed accordingly.

### CODE REVIEW

**Comment by shibatch** [comment]
The reason that I changed CMakeLists.txt is that the location of sleefdft.h is changed from include to src/dft/include.

I want to keep makefiles for cleaning up files like *~ and *.o.

**Comment by shibatch** [comment]
*~ is generated when I edit files.
Usually I have a.out and *.s files in the directories.
Makefiles are not only for building, but there are other uses.

**Comment by fpetrogalli-arm** [comment]
> *~ is generated when I edit files.
> Usually I have a.out and *.s files in the directories.

yeah, I still think you should add a `.gitignore` file listing all what has to be considered junk in the source folder, not craft makefiles around that.

> Makefiles are not only for building, but there are other uses.

Not under  the `src` folder. Am I missing something?

**Comment by shibatch** [comment]
I don't know how you edit and debug the programs, but in my style, I make lots of junk files under src directory.
Don't you want to remove junk files under src directory?

**Comment by fpetrogalli-arm** [comment]
> I don't know how you edit and debug the programs, but in my style, I make lots of junk files under src directory.

Of course I do have a lot of junk in the tree of my project. we are all in the same boat! :)

> Don't you want to remove junk files under src directory?

Of course I do: `git clean [-f]` (careful with the `-f`).

**Comment by shibatch** [comment]
Rebased. The new PR is https://github.com/shibatch/sleef/pull/175.

**Pull request closed without merging**
