### PR TITLE
Fix compilation under Windows with MinGW

### PR DESCRIPTION
**Pull request by nxrighthere**
The compiler-specific condition for `type` and `cat` is incorrect. Also `<io.h>` is missed for `_get_osfhandle`.

### CODE REVIEW

**Comment by nxrighthere** [comment]
What's wrong with the Jenkins? The first commit with `WIN32` didn't pass the build, the second is pending for almost 5 hours.

**Comment by shibatch** [comment]
@nxrighthere Thank you for your commit!
I am sorry, but Jenkins is not working properly now, due to expiration of emulator.
I will fix it soon.

**Comment by yuyichao** [comment]
I'm not sure what's the correct condition but this breaks my compilation under msys2 using `makepkg-mingw` for `mingw64` ....

**Comment by nxrighthere** [comment]
On which OS?

**Comment by yuyichao** [comment]
Windows 10

**Comment by yuyichao** [comment]
[This](https://github.com/nacs-lab/nacs-pkgs/blob/c84ada62e2d64efd0ce34f4ce4c4dda1b50a146f/windows/mingw-w64-sleef-git/PKGBUILD) was the `PKGBUILD` (the master branch has one additional patch to revert this change).

The `build.make` has a line like `type C:\X\Y\Z >> ...` and the `type` gives an error about not being able to fine `C:XYZ`.

**Comment by nxrighthere** [comment]
I think the condition should be then `if(MSVC OR MINGW AND WIN32 AND NOT MSYS)` to separate standalone MinGW and the one under MSYS2.

**Comment by yuyichao** [comment]
That should cover my case for sure.

However, I don't really use windows and have no idea what's the difference between all these posix like environment for windows so I can't say what should be the correct logic ...... = = ....

**Comment by nxrighthere** [comment]
If you use the standalone MinGW then `cat` is not available since it's a UNIX utility and `type` works just fine. In your case I think `cat` is available under MSYS2 so we just need to separate the two.

**Comment by yuyichao** [comment]
Sounds fair. What I mainly don't understand is why does `type` **not** work for me if it works with the standalone mingw.

**Comment by nxrighthere** [comment]
Good question, I'm not using MSYS2, so can't explain where the problem is.

**Comment by yuyichao** [comment]
In particular, for me, the `build.make` was executed by `/bin/sh`, which use the shell builtin `type` command rather than the windows cmd command (the error message for file not found are different and the shell builtin one also doesn't support `C:\...` paths somehow...). The command line argument given to it is also escaped incorrectly causing all the `\` to be missing from the file name....

I just tried using the `mingw-w64-x86_64-make` package instead of the `make` package for the `make` (`mingw32-make`) command and it didn't make a difference..... (they both pick up `/bin/sh`)

**Comment by shibatch** [comment]
One solution could be to build a command for displaying the content of a file from a source code.
I tried to do that before, but this proposal was rejected.

https://github.com/shibatch/sleef/pull/138

**Pull request merged**
