### PR TITLE
Fix sleef.h generation on rebuilds

### LINKED ISSUE #349: Incorrect sleef.h gets generated when SLEEF is added with add_subdirectory
I tried to add SLEEF checked out to `${PROJECT_SOURCE_DIR}/thirdparty/sleef` as follows:
```
set(sleef_SOURCE_DIR "${PROJECT_SOURCE_DIR}/thirdparty/sleef")
set(sleef_BINARY_DIR "${CMAKE_BINARY_DIR}/sleef")
set(SLEEF_SHOW_CONFIG OFF)
set(BUILD_DFT OFF)
set(BUILD_GNUABI_LIBS OFF)
set(BUILD_TESTS OFF)
set(BUILD_INLINE_HEADERS ON)
add_subdirectory(${sleef_SOURCE_DIR} ${sleef_BINARY_DIR} EXCLUDE_FROM_ALL)
```
Building it gives output like
```
[9/84] Generating include/renameavx512f.h
Generating renameavx512f.h: mkrename finz_ 8 16 avx512f
[10/84] Generating ../../include/sleefinline_avx512f.h
Generating sleefinline_avx512f.h
[11/84] Generating include/renameavx512fnofma.h
Generating renameavx512fnofma.h: mkrename cinz_ 8 16 avx512fnofma
[12/84] Generating ../../include/sleefinline_avx512fnofma.h
Generating sleefinline_avx512fnofma.h
[13/84] Generating include/renameavx.h
Generating renameavx.h: mkrename cinz_ 4 8 avx
[14/84] Generating ../../include/sleefinline_avx.h
Generating sleefinline_avx.h
[15/84] Generating include/renameavx2128.h
Generating renameavx2128.h: mkrename finz_ 2 4 avx2128
[16/84] Generating ../../include/sleefinline_avx2128.h
Generating sleefinline_avx2128.h
[17/84] Generating include/renameavx2.h
Generating renameavx2.h: mkrename finz_ 4 8 avx2
[18/84] Generating include/renamesse4.h
Generating renamesse4.h: mkrename cinz_ 2 4 sse4
[23/84] Generating include/renamefma4.h
Generating renamefma4.h: mkrename finz_ 4 8 fma4
[24/84] Generating ../../include/sleef.h
Generating sleef.h: mkrename cinz_ 2 4 __m128d __m128 __m128i __m128i __SSE2__
Generating sleef.h: mkrename cinz_ 2 4 __m128d __m128 __m128i __m128i __SSE2__ sse2
Generating sleef.h: mkrename cinz_ 2 4 __m128d __m128 __m128i __m128i __SSE2__ sse4
Generating sleef.h: mkrename cinz_ 4 8 __m256d __m256 __m128i struct\ {\ __m128i\ x,\ y;\ } __AVX__
Generating sleef.h: mkrename cinz_ 4 8 __m256d __m256 __m128i struct\ {\ __m128i\ x,\ y;\ } __AVX__ avx
Generating sleef.h: mkrename finz_ 4 8 __m256d __m256 __m128i struct\ {\ __m128i\ x,\ y;\ } __AVX__ fma4
Generating sleef.h: mkrename finz_ 4 8 __m256d __m256 __m128i __m256i __AVX__ avx2
Generating sleef.h: mkrename finz_ 2 4 __m128d __m128 __m128i __m128i __SSE2__ avx2128
Generating sleef.h: mkrename finz_ 8 16 __m512d __m512 __m256i __m512i __AVX512F__
Generating sleef.h: mkrename finz_ 8 16 __m512d __m512 __m256i __m512i __AVX512F__ avx512f
Generating sleef.h: mkrename cinz_ 8 16 __m512d __m512 __m256i __m512i __AVX512F__ avx512fnofma
Generating sleef.h: mkrename cinz_ 1 1 double float int32_t int32_t __STDC__ purec
Generating sleef.h: mkrename finz_ 1 1 double float int32_t int32_t FP_FAST_FMA purecfma
[25/84] Generating include/renamesse2.h
Generating renamesse2.h: mkrename cinz_ 2 4 sse2
[26/84] Generating include/renamepurec_scalar.h
Generating renamepurec_scalar.h: mkrename cinz_ 1 1 purec
[27/84] Generating include/renamepurecfma_scalar.h
Generating renamepurecfma_scalar.h: mkrename finz_ 1 1 purecfma
[28/84] Generating include/renamecuda.h
Generating renamecuda.h: mkrename finz_ 1 1 cuda
[29/84] Generating ../../include/sleefinline_sse4.h
Generating sleefinline_sse4.h
[34/84] Generating ../../include/sleefinline_fma4.h
Generating sleefinline_fma4.h
[40/84] Generating ../../include/sleefinline_purec_scalar.h
Generating sleefinline_purec_scalar.h
[50/84] Building C object sleef/src/libm/CMakeFiles/dispsse_obj.dir/dispsse.c.o
FAILED: sleef/src/libm/CMakeFiles/dispsse_obj.dir/dispsse.c.o 
/usr/bin/clang-9 -DENABLE_ALIAS=1 -DENABLE_AVX2=1 -DENABLE_FMA4=1 -DENABLE_SYS_getrandom=1 -DSLEEF_STATIC_LIBS=1 -I../thirdparty/sleef/src/common -I../thirdparty/sleef/src/arch -Isleef/src/libm/include -I../thirdparty/sleef/src/libm -Isleef/include -Wall -Wno-unused -Wno-attributes -Wno-unused-result -ffp-contract=off -fno-math-errno -fno-trapping-math -g   -msse2 -std=gnu99 -MD -MT sleef/src/libm/CMakeFiles/dispsse_obj.dir/dispsse.c.o -MF sleef/src/libm/CMakeFiles/dispsse_obj.dir/dispsse.c.o.d -o sleef/src/libm/CMakeFiles/dispsse_obj.dir/dispsse.c.o   -c sleef/src/libm/dispsse.c
In file included from sleef/src/libm/dispsse.c:24:
sleef/include/sleef.h:10:1: error: unknown type name 'IMPORT'
IMPORT CONST __m128d Sleef_sind2_u35(__m128d);
^
...
```
(many more errors). 

Checking `sleef.h` shows it's generated wrong and starts with
```
#ifdef __SSE2__

#ifndef Sleef___m128d_2_DEFINED
typedef struct {
  __m128d x, y;
} Sleef___m128d_2;
#define Sleef___m128d_2_DEFINED
#endif
```
instead of expected 
```
#ifndef __SLEEF_H__
#define __SLEEF_H__
```
It's also unstable; sometimes the header gets generated correctly, and sometime it has the expected header but loses the footer, with the as in #321. That gave me the idea to use sequential build `cmake --build . --target sleef -j1` (even under Ninja) but it didn't help.

Using 
```
set(sleef_SOURCE_DIR "${PROJECT_SOURCE_DIR}/thirdparty/sleef")
set(sleef_BINARY_DIR "${CMAKE_BINARY_DIR}/sleef")
externalproject_add(sleef
    SOURCE_DIR "${sleef_SOURCE_DIR}"
    CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_INSTALL_PREFIX=${sleef_BINARY_DIR} -DCMAKE_BUILD_TYPE=Release -DSLEEF_SHOW_CONFIG=false -DBUILD_SHARED_LIBS=false -DBUILD_DFT=false -DBUILD_GNUABI_LIBS=false -DBUILD_TESTS=false -DBUILD_INLINE_HEADERS=true)
```
instead of `add_subdirectory` seems to be more reliable but I've still seen incorrect header generated.

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #349

`sleef.h` is being generated incorrectly on rebuilds. Bisecting the issue led to #314 which replaced a copy with cmake's `configure_file`. Since the configure isn't part of `SLEEF_HEADER_COMMANDS`, it might not get called in the right order and so there's no guarantee the header will be written.  This fixes the issue by configuring to a separate file and using the copy command on that file instead.

### CODE REVIEW

**Comment by shibatch** [comment]
Could you give a sequence of commands for reproducing the problem?

**Comment by peterbell10** [comment]
I don't know the minimal set of commands. I was building pytorch which builds sleef with `add_subdirectory` and building twice in a row without source changes was enough to fail the build.

**Comment by peterbell10** [comment]
Okay, here's a minimal failure. Starting from the root of a clean checkout, just configure and build sleef twice in a row:
```sh
mkdir build && cd build
cmake ..
cmake --build .
cmake ..
cmake --build .
```

Re-running cmake configures the file and overwrites sleef.h but the rest of the header generation doesn't happen. `include/sleef.h` contains only the header template `sleeflibm_header.h.org`

**Comment by shibatch** [comment]
Okay. Thanks. I just wanted to add a test for this problem.
I will do that after I merge this patch.

**Pull request merged**
