### PR TITLE
[SVE] Remove all instances of sizeless structures

### PR DESCRIPTION
**Pull request by shibatch**
This patch removes all instances of sizeless structures, as stated in issue https://github.com/shibatch/sleef/issues/309.

It still does not build with gcc-10 with SVE because of the ICE. Please help me coming up with a workaround.

### CODE REVIEW

**Comment by PierreBlanchard** [comment]
Hello Naoki! Thanks a lot for working on that patch.
I got an ICE as well (see below), can you confirm it is the same one you get? I'm trying to extract a small reproducer and I will investigate where it could be coming from.

```
during RTL pass: pro_and_epilogue
/home/piebla01/math-libs/sleef/src/libm/sleefsimdsp.c: In function ‘_ZGVsNxv_sinf_u35’:
/home/piebla01/math-libs/sleef/src/libm/sleefsimdsp.c:510:1: internal compiler error: Segmentation fault
  510 | }
      | ^
0xb35063 crash_signal
	/space/piebla01/gcc-10.1.0/gcc/toplev.c:328
0xdd0598 aarch64_expand_epilogue(bool)
	/space/piebla01/gcc-10.1.0/gcc/config/aarch64/aarch64.c:8188
0x1082ecb gen_epilogue()
	/space/piebla01/gcc-10.1.0/gcc/config/aarch64/aarch64.md:829
0xdc892b target_gen_epilogue
	/space/piebla01/gcc-10.1.0/gcc/config/aarch64/aarch64.md:7245
0x8985db make_epilogue_seq
	/space/piebla01/gcc-10.1.0/gcc/function.c:5823
0x898b5f thread_prologue_and_epilogue_insns()
	/space/piebla01/gcc-10.1.0/gcc/function.c:5926
0x898c2f rest_of_handle_thread_prologue_and_epilogue
	/space/piebla01/gcc-10.1.0/gcc/function.c:6395
0x898c2f execute
	/space/piebla01/gcc-10.1.0/gcc/function.c:6471
```

**Comment by shibatch** [comment]
Hello Pierre,

I have already reported the ICE to Francesco, but the following is the shortened source code for reproducing the ICE. It is pretty long for pasting into a github comment, but I cannot shorten it further.

```
// gcc-10 -O2 -march=armv8-a+sve bug-sve-gcc10.c -S

#include <arm_sve.h>

#define ptrue svptrue_b8()

// Mask definition
typedef svint32_t vmask;
typedef svbool_t vopmask;

// Single precision definitions
typedef svfloat32_t vfloat;
typedef svint32_t vint2;

// Double precision definitions
typedef svfloat64_t vdouble;
typedef svint32_t vint;

// vmask2 is used mainly used in quad-precision functions
typedef svint32x2_t vmask2;
static vmask vm2getx_vm_vm2(vmask2 v) { return svget2_s32(v, 0); }
static vmask vm2gety_vm_vm2(vmask2 v) { return svget2_s32(v, 1); }
static vmask2 vm2setxy_vm2_vm_vm(vmask x, vmask y) { return svcreate2_s32(x, y); }

// masking predicates
#define ALL_TRUE_MASK svdup_n_s32(0xffffffff)

static inline int vtestallones_i_vo32(vopmask g) {
  svbool_t pg = svptrue_b32();
  return (svcntp_b32(pg, g) == svcntw());
}

// Mask <--> single precision reinterpret
static inline vmask vreinterpret_vm_vf(vfloat vf) {
  return svreinterpret_s32_f32(vf);
}
static inline vfloat vreinterpret_vf_vm(vmask vm) {
  return svreinterpret_f32_s32(vm);
}
static inline vint2 vreinterpret_vi2_vf(vfloat vf) {
  return svreinterpret_s32_f32(vf);
}

/****************************************/
/* Single precision FP operations */
/****************************************/
// Broadcast
static inline vfloat vcast_vf_f(float f) { return svdup_n_f32(f); }

// Add, Sub, Mul
static inline vfloat vadd_vf_vf_vf(vfloat x, vfloat y) {
  return svadd_f32_x(ptrue, x, y);
}
static inline vfloat vsub_vf_vf_vf(vfloat x, vfloat y) {
  return svsub_f32_x(ptrue, x, y);
}
static inline vfloat vmul_vf_vf_vf(vfloat x, vfloat y) {
  return svmul_f32_x(ptrue, x, y);
}

// |x|, -x
static inline vfloat vabs_vf_vf(vfloat f) { return svabs_f32_x(ptrue, f); }


// int <--> float conversions
static inline vint2 vtruncate_vi2_vf(vfloat vf) {
  return svcvt_s32_f32_x(ptrue, vf);
}
static inline vfloat vcast_vf_vi2(vint2 vi) {
  return svcvt_f32_s32_x(ptrue, vi);
}
static inline vint2 vcast_vi2_i(int i) { return svdup_n_s32(i); }
static inline vint2 vrint_vi2_vf(vfloat d) {
  return svcvt_s32_f32_x(ptrue, svrintn_f32_x(ptrue, d));
}

static inline vfloat vmla_vf_vf_vf_vf(vfloat x, vfloat y, vfloat z) { return vadd_vf_vf_vf(vmul_vf_vf_vf(x, y), z); }


static inline vfloat vrint_vf_vf(vfloat vf) {
  return svrintn_f32_x(svptrue_b32(), vf);
}

static inline vint2 vsub_vi2_vi2_vi2(vint2 x, vint2 y) {
  return svsub_s32_x(ptrue, x, y);
}


// Shifts
#define vsrl_vi2_vi2_i(x, c)                                                   \
  svreinterpret_s32_u32(svlsr_n_u32_x(ptrue, svreinterpret_u32_s32(x), c))

static inline vopmask vneq_vo_vf_vf(vfloat x, vfloat y) {
  return svcmpne_f32(ptrue, x, y);
}
static inline vopmask vlt_vo_vf_vf(vfloat x, vfloat y) {
  return svcmplt_f32(ptrue, x, y);
}
static inline vopmask visinf_vo_vf(vfloat d) {
  return svcmpeq_n_f32(ptrue, vabs_vf_vf(d), __builtin_inff());
}

static inline vmask vor_vm_vo32_vm(vopmask x, vmask y) {
  return svsel_s32(x, ALL_TRUE_MASK, y);
}

static inline vfloat vgather_vf_p_vi2(const float *ptr, vint2 vi2) {
  return svld1_gather_s32index_f32(ptrue, ptr, vi2);
}

typedef svfloat32x2_t vfloat2;
static vfloat  vf2getx_vf_vf2(vfloat2 v) { return svget2_f32(v, 0); }
static vfloat  vf2gety_vf_vf2(vfloat2 v) { return svget2_f32(v, 1); }
static vfloat2 vf2setx_vf2_vf2_vf(vfloat2 v, vfloat d) { return svset2_f32(v, 0, d); }
static vfloat2 vf2setxy_vf2_vf_vf(vfloat x, vfloat y)  { return svcreate2_f32(x, y); }

static inline vfloat2 vcast_vf2_vf_vf(vfloat h, vfloat l) { return vf2setxy_vf2_vf_vf(h, l); }

static inline vfloat2 dfmul_vf2_vf_vf(vfloat x, vfloat y) {
  vfloat s = vmul_vf_vf_vf(x, y);
  return vf2setxy_vf2_vf_vf(s, s);
}

static inline vfloat2 dfadd2_vf2_vf2_vf2(vfloat2 x, vfloat2 y) {
  return vf2setxy_vf2_vf_vf(vadd_vf_vf_vf(vf2getx_vf_vf2(x), vf2getx_vf_vf2(y)),
                            vadd_vf_vf_vf(vf2gety_vf_vf2(x), vf2gety_vf_vf2(y)));
}

static inline vint2 vilogb2k_vi2_vf(vfloat d) {
  vint2 q = vreinterpret_vi2_vf(d);
  q = vsrl_vi2_vi2_i(q, 23);
  q = vsub_vi2_vi2_vi2(q, vcast_vi2_i(0x7f));
  return q;
}

typedef svfloat32x2_t fi_t;

static vfloat figetd_vf_di(fi_t d) { return svget2_f32(d, 0); }
static vint2 figeti_vi2_di(fi_t d) { return svreinterpret_s32_f32(svget2_f32(d, 1)); }
static fi_t fisetdi_fi_vf_vi2(vfloat d, vint2 i) {
  return svcreate2_f32(d, svreinterpret_f32_s32(i));
}

typedef svfloat32x3_t dfi_t;

static vfloat2 dfigetdf_vf2_dfi(dfi_t d) {
  return svcreate2_f32(svget3_f32(d, 0), svget3_f32(d, 1));
}
static vint2 dfigeti_vi2_dfi(dfi_t d) { return svreinterpret_s32_f32(svget3_f32(d, 2)); }
static dfi_t dfisetdfi_dfi_vf2_vi2(vfloat2 v, vint2 i) {
  return svcreate3_f32(svget2_f32(v, 0), svget2_f32(v, 1),
                       svreinterpret_f32_s32(i));
}
static dfi_t dfisetdf_dfi_dfi_vf2(dfi_t dfi, vfloat2 v) {
  return svcreate3_f32(svget2_f32(v, 0), svget2_f32(v, 1), svget3_f32(dfi, 2));
}

static inline fi_t rempisubf(vfloat x) {
  vfloat y = vrint_vf_vf(vmul_vf_vf_vf(x, vcast_vf_f(4)));
  vint2 vi = vtruncate_vi2_vf(vsub_vf_vf_vf(y, vmul_vf_vf_vf(vrint_vf_vf(x), vcast_vf_f(4))));
  return fisetdi_fi_vf_vi2(vsub_vf_vf_vf(x, vmul_vf_vf_vf(y, vcast_vf_f(0.25))), vi);
}

static inline dfi_t rempif(vfloat a) {
  extern const float rempitabsp[];

  vfloat2 x, y;
  vint2 ex = vilogb2k_vi2_vf(a);
  vint2 q = ex;
  x = dfmul_vf2_vf_vf(a, vgather_vf_p_vi2(rempitabsp, ex));
  fi_t di = rempisubf(vf2getx_vf_vf2(x));
  q = figeti_vi2_di(di);
  x = dfadd2_vf2_vf2_vf2(x, y);
  di = rempisubf(vf2getx_vf_vf2(x));
  x = vf2setx_vf2_vf2_vf(x, figetd_vf_di(di));
  y = vcast_vf2_vf_vf(vgather_vf_p_vi2(rempitabsp+2, ex), vgather_vf_p_vi2(rempitabsp+3, ex));
  x = dfadd2_vf2_vf2_vf2(x, y);
  return dfisetdfi_dfi_vf2_vi2(x, q);
}

vfloat xsinf(vfloat d) {
  vint2 q;
  vfloat u, s, r = d;

  if ((vtestallones_i_vo32(vlt_vo_vf_vf(vabs_vf_vf(d), vcast_vf_f(0))))) {
    q = vrint_vi2_vf(d);
    u = vcast_vf_vi2(q);
    d = vmla_vf_vf_vf_vf(u, u, d);
  } else {
    dfi_t dfi = rempif(d);
    q = dfigeti_vi2_dfi(dfi);
    dfi = dfisetdf_dfi_dfi_vf2(dfi, dfigetdf_vf2_dfi(dfi));
    d = vadd_vf_vf_vf(vf2getx_vf_vf2(dfigetdf_vf2_dfi(dfi)), vf2gety_vf_vf2(dfigetdf_vf2_dfi(dfi)));
    d = vreinterpret_vf_vm(vor_vm_vo32_vm(visinf_vo_vf(r), vreinterpret_vm_vf(d)));
  }

  u = vcast_vf_f(2.6083159809786593541503e-06f);
  u = vmla_vf_vf_vf_vf(u, d, vcast_vf_f(-0.0001981069071916863322258f));

  return u;
}
```

**Comment by rsandifo-arm** [comment]
Thanks for reporting the GCC ICE.  I've just pushed [a fix](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=c082cb8a2523d8c5afe5710e265bc72dd71aa60b) to the gcc-10 branch .  The patch also applies cleanly to the GCC 10.1 sources, if you're building from tarballs rather than git.

A workaround for broken compilers is to compile with `-fno-shrink-wrap`, although that will lose some optimisation.

**Comment by shibatch** [comment]
Hello Richard,

Thank you for fixing the bug. I still cannot build the library with gcc-10 because of "Error: unknown pseudo-op: `.variant_pcs'." I have to try with newer binutils.

**Comment by shibatch** [comment]
I believe the following is another bug in gcc-10.

```
[neon]~/work/sleef3/bug/sve-gcc10-2$ cat bug2.c
#include <stdio.h>
#include <stdint.h>
#include <arm_sve.h>

int main(void) {
  uint64_t a[64], u[svcntd()];
  for(int i=0;i<sizeof(a);i++) ((unsigned char *)&a)[i] = i;
  svst1_s32(svptrue_b8(), (void *)&u, svld1_s32(svptrue_b8(), (int32_t *)&a));
  for(int i=0;i<svcntd();i++) printf("%016lx:", (unsigned long)(u[i]));
  printf("\n");
}
[neon]~/work/sleef3/bug/sve-gcc10-2$ armclang -O3 -march=armv8-a+sve bug2.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
0706050403020100:0f0e0d0c0b0a0908:
[neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -fno-shrink-wrap -O1 -march=armv8-a+sve bug2.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
0706050403020100:0f0e0d0c0b0a0908:
[neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -fno-shrink-wrap -O2 -march=armv8-a+sve bug2.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
0000007f97201ec8:0000000000000000:
[neon]~/work/sleef3/bug/sve-gcc10-2$
```

**Comment by shibatch** [comment]
And this one?

```
[neon]~/work/sleef3/bug/sve-gcc10-2$ cat bug3.c
#include <stdio.h>
#include <arm_sve.h>

int main(void) {
  for(int i=0;i<svcntd();i++) printf("x");
  printf("\n");
}
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie --version
20.0-14
[neon]~/work/sleef3/bug/sve-gcc10-2$ armclang -O3 -march=armv8-a+sve bug3.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=256 ./a.out
xxxx
[neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -fno-shrink-wrap -O1 -march=armv8-a+sve bug3.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=256 ./a.out
xxxx
[neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -fno-shrink-wrap -O2 -march=armv8-a+sve bug3.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
xx
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=256 ./a.out
xxxxxxxxxxxxxxxxxxxxxxxxxx (gets into an infinite loop)
```

**Comment by shibatch** [comment]
The optimization flags causing those bugs are -fstrict-aliasing for bug2.c, and -ftree-vrp for bug3.c.

**Comment by shibatch** [comment]
So, I succeeded in building the library with "-fno-shrink-wrap -fno-strict-aliasing -fno-tree-vrp" options. I added a new CI setting with gcc-10 to .travis.yml. In this setting, binutils-2.34 and qemu 5.0.0 built by me is used. These are downloaded from my web server and installed under /opt/local.

**Comment by rsandifo-arm** [comment]
Thanks for raising this.

I'll try to fix `bug3.c` for GCC 10.2 and report back.  Thanks for tracking down which pass caused it.

For `bug2.c`: this kind of behaviour is actually expected.  The reason is that, at the language level, the SVE load and store intrinsics act very much like the individual scalar accesses would.  For example, `svld1_s32` loads data as `int32_t` elements rather than as typeless data or individual bytes.  This means that the aliasing rules for `svld1_s32` and `svst1_s32` are the same as they are for individual `int32_t` accesses.  The code therefore invokes undefined behaviour because it accesses `uint64_t` objects as though they were `int32_t` objects.

If an array contains `uint64_t` objects, then according to the default aliasing rules, they need to be loaded and stored using `svld1_u64` and `svst1_u64`.  The vectors can be converted to and from the processing type using things like `svreinterpret_s32_u64`.

Like you say, `-fno-strict-aliasing` is supported as a way of opting out of the alias rules, if you'd prefer to keep things as they are.  This is likely to reduce optimisation though.

**Comment by shibatch** [comment]
Thank you for your explanation. But I still don't understand why it is undefined.
Is it because the alignments of those two data types are different? I believe casting from uint64_t * to int32_t * is permitted. Is it because conversion between those two data types are not defined? I believe conversion is straightforward.

```
[neon]~/work/sleef3/bug/sve-gcc10-2$ cat bug2y.c
#include <stdio.h>
#include <arm_sve.h>

int main(void) {
  uint32_t u[svcntw()];
  svst1_u64(svptrue_b8(), (void *)u, svdup_n_u64(1));
  for(int i=0;i<svcntw();i++) printf("%08x", (unsigned int)(u[i]));
  printf("\n");
  //
  uint64_t v[svcntd()];
  svst1_u32(svptrue_b8(), (void *)v, svdup_n_u32(1));
  for(int i=0;i<svcntd();i++) printf("%016lx", (unsigned long int)(v[i]));
  printf("\n");
}
[neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -Wall -Wcast-align -O1 -march=armv8-a+sve bug2y.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
00000001000000000000000100000000
00000001000000010000000100000001
[neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -Wall -Wcast-align -O2 -march=armv8-a+sve bug2y.c
[neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
d6e3d6800000007fa74b51e00000007f
00000000000000040000007fa3a26000
[neon]~/work/sleef3/bug/sve-gcc10-2$
```

**Comment by rsandifo-arm** [comment]
Hi.  The problem isn't so much with the cast itself, but that the intrinsics implicitly dereference their pointer arguments.  C and C++ only allow a pointer `ptr` of type `T *` to be dereferenced if the “real” runtime type of the object at `ptr` is compatible with `T` up to a certain point.  The exact rules are quite complicated, but https://stackoverflow.com/a/51228315 has a good write-up.

So for example in:
```
uint64_t x;
for (int i = 0; i < sizeof(uint64_t); ++i) ((unsigned char *)&x)[i] = 1; // OK
*(uint32_t *)&x = 2; // UB
```
the loop setting up the `uint64_t` is OK (and the loop in `bug2.c` is OK) because accessing a `uint64_t` using character types is explicitly allowed.  But accessing the `uint64_t` object as though it had `uint32_t` is undefined behaviour.  The intrinsics inherit this behaviour because (at the language level) they act like individual scalar accesses.

**Comment by shibatch** [comment]
Okay, I now understand.
I will modify the code in SLEEF to comply with the aliasing rules.

However, in my opinion, it would be easier for programmers if the aliasing rules are not set in this way, because of the following reasons.

* There is no clear rule that specifies which aliasing rule is applied to the load and store intrinsic functions. Since data is conceptually stored in the memory, some programmers might assume that the memcpy rule is applied.
* In x86 intrinsics, there is only one integer data type for each vector width. For example, __m128i is the only integer type with 128-bit width. This data type is used for operations with any of 8-bit, 32-bit, 64-bit, signed and unsigned integer types. So, the strict-aliasing rule does not apply. In terms of portability of codes, I think it would be less troublesome to apply the memcpy rule to load and store intrinsics.

These are just my thoughts.

**Comment by shibatch** [comment]
I modified the code in SLEEF so that it complies with the aliasing rules.
I need additional modification to the DFT, and I will do it in another PR.

**Comment by PierreBlanchard** [comment]
Dear Naoki,
Thanks to your patch I was able to compile the SVE routines successfully with a gcc-10.1.0 (+latest binutils) built locally (from a tarball). All tests pass except the fft ones but I guess that is the DFT related issue you mentioned in your previous message, that you are looking to fix.
Had a look through the code earlier this month and it all looked good to me.
Thanks a lot for this effort as well as @rsandifo-arm for your help on this!

**Comment by rsandifo-arm** [comment]
> ```
> [neon]~/work/sleef3/bug/sve-gcc10-2$ cat bug3.c
> #include <stdio.h>
> #include <arm_sve.h>
> 
> int main(void) {
>   for(int i=0;i<svcntd();i++) printf("x");
>   printf("\n");
> }
> [neon]~/work/sleef3/bug/sve-gcc10-2$ armie --version
> 20.0-14
> [neon]~/work/sleef3/bug/sve-gcc10-2$ armclang -O3 -march=armv8-a+sve bug3.c
> [neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=256 ./a.out
> xxxx
> [neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -fno-shrink-wrap -O1 -march=armv8-a+sve bug3.c
> [neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=256 ./a.out
> xxxx
> [neon]~/work/sleef3/bug/sve-gcc10-2$ gcc-10 -fno-shrink-wrap -O2 -march=armv8-a+sve bug3.c
> [neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=128 ./a.out
> xx
> [neon]~/work/sleef3/bug/sve-gcc10-2$ armie -msve-vector-bits=256 ./a.out
> xxxxxxxxxxxxxxxxxxxxxxxxxx (gets into an infinite loop)
> ```

Thanks for reporting this.  It was fixed in GCC 10.2, which was released earlier today.

**Pull request merged**
