### PR TITLE
Build static bins if BUILD_SHARED_LIBS is defined

### PR DESCRIPTION
**Pull request by steplong**
Search for the static libraries instead and add -static to CFLAGS

### CODE REVIEW

**Comment by steplong** [comment]
@fpetrogalli it looked like BUILD_SHARED_LIBS only builds the libraries statically. Maybe, I should add a new variable like BUILD_SHARED_BINS instead of using BUILD_SHARED_LIBS. Also, it looked like the tests were failing silently when they ran suspiciously fast. If I passed -VV to ctest, it showed that it wasn't passing the interpreter to QEMU.

**Comment by shibatch** [comment]
I don't understand the purpose well.
I think adding -static should be done automatically by cmake when BUILD_SHARED_LIBS=FALSE?

**Comment by steplong** [comment]
When I set BUILD_SHARED_LIBS=FALSE, it only determined whether a static archive or shared object was built. The test executables that were going to be ran with QEMU were still dynamically linked.

**Comment by shibatch** [comment]
Okay, but why do you need static executables?

**Comment by steplong** [comment]
On some of the machines we will run the tests on, we might not have an elf interpreter to pass to QEMU.

**Comment by shibatch** [comment]
You see, builds on mac are failing with the current patch.
Can you fix this problem?

**Comment by shibatch** [comment]
Please refer to the following page.

https://stackoverflow.com/questions/24648357/compiling-a-static-executable-with-cmake

**Comment by steplong** [comment]
Hmmm, for the appveyor build, it looks like it can't find OpenSSL. Also, I can't seem to see the details for the jenkins jobs. I get a 404 when I click the details link.

**Comment by shibatch** [comment]
Maybe it is better to add a separate flag to enable this feature.

**Comment by steplong** [comment]
That makes sense. I'll add BUILD_STATIC_TEST_BINS then.

**Pull request merged**
