### PR TITLE
[revert] This is just a test for CI.

### PR DESCRIPTION
**Pull request by fpetrogalli-arm**
Is this a real falure of SLEEF or a CI configuration poblem?

    https://travis-ci.org/shibatch/sleef/jobs/285218079

### CODE REVIEW

**Comment by fpetrogalli-arm** [comment]
@xoofx @shibatch So, yes, CI is broken on OSX due to the ruby interpreter being out of date with what homebrew expects as minimal version: https://travis-ci.org/shibatch/sleef/jobs/285452667#L1577

**Comment by shibatch** [comment]
Can't you use MacPorts instead?

**Comment by fpetrogalli-arm** [comment]
@shibatch I'd rather not use MacPorts because `homebrew` seems to be "natively" supported by Travis CI.

**Comment by fpetrogalli-arm** [comment]
I have self-approved this one because we need CI back again asap.

**Pull request merged**
