### PR TITLE
Make building tests optional

### PR DESCRIPTION
**Pull request by cpuhrsch**
This patch adds the following three CMAKE build option.

* BUILD_TESTS : Turned on by default. libm-tester and dft-tester will be built.

### CODE REVIEW

**Comment by shibatch** [comment]
Why do you need this patch? If my understanding is correct, tests of the external project are defined only if such options are specified to ExternalProject_Add.

**Comment by shibatch** [comment]
Okay, please sort out other problems. I will merge this patch after the PR for pytorch is approved.

**Comment by shibatch** [comment]
I think this PR can be closed now.

**Comment by cpuhrsch** [comment]
Yes, thank!

**Pull request closed without merging**
