### PR TITLE
Mark Sleef_rempitabq* constants as static

### PR DESCRIPTION
**Pull request by luhenry**
Without marking it static, it fails to compile when including multiple sleefinline_*.h into the same compilation unit.

Co-Authored-By: Hamlin Li <hamlin@rivosinc.com>

### CODE REVIEW

**Review by Hamlin-Li — APPROVED** [review]
Looks good. Thanks

**Comment by joeramsay** [comment]
Would you mind adding static to `Sleef_rempitabsp` as well?
> including multiple sleefinline_*.h into the same compilation unit.

This should already be addressed by the include guard around the rempi tables. Are you sure the issue isn't from linking multiple TUs that all included the header and used the table?

**Comment by luhenry** [comment]
@joeramsay fixed.

**Comment by luhenry** [comment]
@blapie hi, what would be the path forward for this? Thanks!

**Comment by nSircombe** [comment]
Hi @luhenry, it should be possible to move this on soon (see https://github.com/shibatch/sleef/pull/537#issuecomment-2063895882)

**Pull request merged**
